org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

kotlin.code.style=official

android.useAndroidX=true
android.nonTransitiveRClass=true

appVersion=2.0.0

kotlinVersion=2.2.21
gdxVersion=1.14.2
ktxVersion=1.13.1-rc1
gdxTeaVMVersion=1.4.0
gdxTeaVMPluginVersion=1.6.0
roboVMVersion=2.3.25
androidPluginVersion=8.11.2
junitVersion=5.11.4
